# Generated by Django 3.1.12 on 2021-06-30 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0003_auto_20210630_1126'),
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.DateTimeField(auto_now_add=True, verbose_name='借閱時間')),
                ('returned', models.DateTimeField(null=True, verbose_name='歸還時間')),
                ('Classrooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classrooms')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrower.borrower')),
            ],
        ),
    ]
