# Generated by Django 3.1.12 on 2021-06-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='教室名')),
                ('period', models.CharField(max_length=255, verbose_name='節次')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('preface', models.ImageField(upload_to='', verbose_name='圖片')),
            ],
        ),
    ]
