# Generated by Django 3.1.12 on 2021-06-30 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_remove_classrooms_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='preface',
            new_name='image',
        ),
    ]
